name: youtube_explode_dart
description: A port in dart of the youtube explode library. Supports several API functions without the need of Youtube API Key.
version: 1.10.10+2

homepage: https://github.com/Hexer10/youtube_explode_dart

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  freezed_annotation: ^1.1.0
  html: ^0.15.0
  http: ^0.13.4
  http_parser: ^4.0.0
  json_annotation: ^4.4.0
  meta: ^1.7.0
  xml: ^5.3.1

dev_dependencies:
  build_runner: ^2.1.5
  console: ^4.1.0
  freezed: ^1.1.0
  json_serializable: ^6.1.1
  lint: ^1.8.1
  test: ^1.19.5

false_secrets:
  - "lib/src/reverse_engineering/youtube_http_client.dart"
  - "lib/src/reverse_engineering/clients/embedded_player_client.dart"
