name: youtube_explode_dart
description: A port in dart of the youtube explode library. Supports several API functions without the need of Youtube API Key.
version: 2.0.0+1
homepage: https://github.com/Hexer10/youtube_explode_dart

topics:
  - youtube
  - lints
  - video
  - streams

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.16.0
  freezed_annotation: ^2.2.0
  html: ^0.15.0
  http: ^1.0.0
  http_parser: ^4.0.0
  json_annotation: ^4.5.0
  meta: ^1.7.0
  source_gen: ^1.4.0
  xml: ^6.1.0

dev_dependencies:
  build_runner: ^2.1.11
  console: ^4.1.0
  freezed: ^2.3.2
  json_serializable: ^6.2.0
  lint: ^2.1.2
  test: ^1.21.1

false_secrets:
  - "lib/src/reverse_engineering/youtube_http_client.dart"
  - "lib/src/videos/video_controller.dart"
