name: youtube_explode_dart
description: A port in dart of the youtube explode library. Supports several API functions without the need of Youtube API Key.
version: 1.9.4

homepage: https://github.com/Hexer10/youtube_explode_dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  equatable: ^2.0.0
  html: ^0.15.0
  http: ^0.13.0
  http_parser: ^4.0.0
  json_annotation: ^4.0.0
  meta: ^1.3.0
  xml: ^5.0.2

dev_dependencies:
  build_runner: ^1.12.2
  console: ^4.0.0
  grinder: ^0.9.0-nullsafety.0
  json_serializable: ^4.1.0
  lint: ^1.5.3
  pedantic: ^1.11.0
  test: ^1.16.8
